### ISSUE TITLE
建议支持指定路径批量选择、全部反向选择

### ISSUE THREAD

**Issue by sls463** [JiuLing-zhang/FindDuplicateFiles#2]
当前软件的自动批量选择功能有一定局限性，以下附演示1举例，点了自动选择按钮软件就会自动批量选择了E盘下的重复文件，但如果我想优先清理掉C盘的重复文件呢，那么这时侯就会发现是不是缺少一个常见的全部反向选择按钮了呢^_^
我试用过不少此类重复文件查找软件，有的自动批量选择有点像黑箱操作，有可能会出现这种情况：我以为它是自动批量选择了E盘下文件夹的重复文件，实际上有可能是它大部分选了E盘下的重复文件，但它又自动零星选择有几个是C盘下文件夹的重复文件，如果我想当然去点了删除，那么就悲剧了，所以我最想要的功能是可以自行选择指定路径的批量选中(见下附演示2)，设想是这样的：点"批量选中重复文件“按钮时会显示出当前已添加查找路径让我自行选择是那个路径下的文件夹

![2 请支持指定路径批量选择、全部反向选择](https://user-images.githubusercontent.com/41649803/156405034-dbfd30d6-7db8-48e4-8e45-986734d9ce0a.gif)
![3 指定路径批量选择演示](https://user-images.githubusercontent.com/41649803/156405072-57ae3241-95e6-4035-9c6c-a79cc15687f5.gif)

**Comment by JiuLing-zhang** [comment]
程序支持单一路径或多个路径（超过2个）的查询，因此选择时展示“已添加的路径”供选择并不合理。
不过这里可以增加一个和上图一样的过滤框，输入过滤条件后，只选中满足条件的文件。

**Comment by sls463** [comment]
补充说明一下：我知道支持多个路径查询，可能我说得不是很清楚，我的设想是这样子的
查询路径： 
路径1
路径2
路径3
路径4
路径5...

查询结果为：
A.xxx   路径1
A.xxx   路径2
A.xxx   路径3
A.xxx   路径4
A.xxx   路径5
B.xxx   路径1
B.xxx   路径2
B.xxx   路径3
B.xxx   路径4
B.xxx   路径5.....

如果增加一个“指定选中路径”按钮，点击后会列出可多选项“路径1、路径2、路径3、路径4、路径5..."，
如果我选了”路径3、路径4、路径5“，然后点”删除“

那么这时候查询结果并不是全部清空，而是仅清掉已选中删除掉的那一部分重复文件
查询结果将更新为：(可以理解为待处理列表，可再次进行选中删除处理，直到全部处理完或放弃处理)
A.xxx   路径1
A.xxx   路径2
B.xxx   路径1
B.xxx   路径2
.....
