### ISSUE TITLE
建议增加脱机目录的查找

### ISSUE THREAD

**Issue by linpeipeng** [JiuLing-zhang/FindDuplicateFiles#4]
### 功能描述

比如要查找的目录可能分布在多块移动硬盘上，平时并没插在电脑上。

### 解决方案

建议要查找的路径所在行增加个建立索引按钮，这样在脱机状态下也能查找。

**Comment by linpeipeng** [comment]
另外可以的话建议增加针对某个文件对于在所要查找目录的重复性检查功能

**Comment by JiuLing-zhang** [comment]
是需要插上硬盘后自动启动查找功能吗？
目前程序只考虑通过前台运行，不使用系统后台服务，因此暂时不考虑增加脱机查询的这种情况。
